import type { MenuItem } from '@/types';
import {
  TORTILLA_CHOICE,
  FAJITA_SIZE,
  ENCHILADA_FLAUTA_SIZE,
  TACO_MEAT_CHOICE,
} from '@/constants/optionGroups';

/** Served with rice, beans, and tortillas. */
export const comboPlates: MenuItem[] = [
  {
    id: 'no-1-carne-asada',
    name: '#1 Carne Asada',
    price: 19.59,
    category: 'Combo Plates',
    channel: 'taqueria',
    optionGroups: [TORTILLA_CHOICE],
  },
  {
    id: 'no-2-pechuga-a-la-parrilla',
    name: '#2 Pechuga a la Parrilla',
    price: 15.99,
    category: 'Combo Plates',
    channel: 'taqueria',
    optionGroups: [TORTILLA_CHOICE],
  },
  {
    id: 'no-3-pechuga-empanizada',
    name: '#3 Pechuga Empanizada',
    price: 15.99,
    category: 'Combo Plates',
    channel: 'taqueria',
    optionGroups: [TORTILLA_CHOICE],
  },
  {
    id: 'no-4-milanesa',
    name: '#4 Milanesa',
    price: 16.59,
    category: 'Combo Plates',
    channel: 'taqueria',
    optionGroups: [TORTILLA_CHOICE],
  },
  {
    id: 'no-5-carnitas',
    name: '#5 Carnitas',
    price: 14.99,
    category: 'Combo Plates',
    channel: 'taqueria',
    optionGroups: [TORTILLA_CHOICE],
  },
  {
    id: 'no-6-fajitas',
    name: '#6 Fajitas',
    price: 16.59,
    category: 'Combo Plates',
    channel: 'taqueria',
    optionGroups: [FAJITA_SIZE, TORTILLA_CHOICE],
  },
  {
    id: 'no-7-fajitas-mix',
    name: '#7 Fajitas Mix',
    price: 18.59,
    category: 'Combo Plates',
    channel: 'taqueria',
    optionGroups: [TORTILLA_CHOICE],
  },
  {
    id: 'no-8-birria-goat',
    name: '#8 Birria Goat',
    price: 15.99,
    category: 'Combo Plates',
    channel: 'taqueria',
    optionGroups: [TORTILLA_CHOICE],
  },
  {
    id: 'no-9-barbacoa',
    name: '#9 Barbacoa',
    price: 15.99,
    category: 'Combo Plates',
    channel: 'taqueria',
    optionGroups: [TORTILLA_CHOICE],
  },
  {
    id: 'no-10-chili-relleno',
    name: '#10 Chili Relleno',
    price: 15.99,
    category: 'Combo Plates',
    channel: 'taqueria',
    optionGroups: [TORTILLA_CHOICE],
  },
  {
    id: 'no-11-bistec-ranchero',
    name: '#11 Bistec Ranchero',
    price: 16.99,
    category: 'Combo Plates',
    channel: 'taqueria',
    optionGroups: [TORTILLA_CHOICE],
  },
  {
    id: 'no-12-chili-verde',
    name: '#12 Chili Verde',
    price: 15.99,
    category: 'Combo Plates',
    channel: 'taqueria',
    optionGroups: [TORTILLA_CHOICE],
  },
  {
    id: 'no-13-mole-poblano',
    name: '#13 Mole Poblano',
    price: 15.99,
    category: 'Combo Plates',
    channel: 'taqueria',
    optionGroups: [TORTILLA_CHOICE],
  },
  {
    id: 'no-14-enchiladas',
    name: '#14 Enchiladas',
    price: 16.99,
    category: 'Combo Plates',
    channel: 'taqueria',
    optionGroups: [ENCHILADA_FLAUTA_SIZE, TORTILLA_CHOICE],
  },
  {
    id: 'no-15-enchiladas-verdes',
    name: '#15 Enchiladas Verdes',
    price: 15.99,
    category: 'Combo Plates',
    channel: 'taqueria',
    optionGroups: [TORTILLA_CHOICE],
  },
  {
    id: 'no-16-flautas',
    name: '#16 Flautas',
    price: 14.99,
    category: 'Combo Plates',
    channel: 'taqueria',
    optionGroups: [ENCHILADA_FLAUTA_SIZE, TORTILLA_CHOICE],
  },
  {
    id: 'no-17-aporreadillo',
    name: '#17 Aporreadillo',
    price: 18.99,
    category: 'Combo Plates',
    channel: 'taqueria',
    optionGroups: [TORTILLA_CHOICE],
  },
  {
    id: 'no-18-tacos',
    name: '#18 Tacos',
    price: 12.99,
    category: 'Combo Plates',
    channel: 'taqueria',
    optionGroups: [TORTILLA_CHOICE, TACO_MEAT_CHOICE],
  },
  {
    id: 'no-19-tacos-dorados',
    name: '#19 Tacos Dorados',
    price: 13.99,
    category: 'Combo Plates',
    channel: 'taqueria',
    optionGroups: [TORTILLA_CHOICE, TACO_MEAT_CHOICE],
  },
  {
    id: 'cheeseburger-w-fries',
    name: 'Cheeseburger w/ Fries',
    price: 12.99,
    category: 'Combo Plates',
    channel: 'taqueria',
  },
];
