import type { MenuItem } from '@/types';
import { SEASONING } from '@/constants/optionGroups';

export const beef: MenuItem[] = [
  {
    id: 'beef-flap-arrachera',
    name: 'Beef Flap/Arrachera',
    price: 16.59,
    category: 'Beef',
    channel: 'market',
    unit: 'Per lb.',
    maxQuantityNote: '10 POUND MAX',
    optionGroups: [SEASONING],
  },
  {
    id: 'chuck-roll-diezmillo-en-trozo',
    name: 'Chuck Roll/Diezmillo En Trozo',
    price: 10.99,
    category: 'Beef',
    channel: 'market',
    unit: 'Per lb.',
    maxQuantityNote: '10 POUND MAX',
  },
  {
    id: 'bbq-beef-ribs-costillas-de-res-bbq',
    name: 'BBQ Beef Ribs/Costillas De Res BBQ',
    price: 11.39,
    category: 'Beef',
    channel: 'market',
    unit: 'Per lb.',
    maxQuantityNote: '10 POUND MAX',
  },
  {
    id: 'ground-beef-carne-molida-de-res',
    name: 'Ground Beef/Carne Molida De Res',
    price: 8.99,
    category: 'Beef',
    channel: 'market',
    unit: 'Per lb.',
    maxQuantityNote: '10 POUND MAX',
  },
  {
    id: 'beef-liver-higado-de-res',
    name: 'Beef Liver/Higado De Res',
    price: 3.69,
    category: 'Beef',
    channel: 'market',
    unit: 'Per lb.',
    maxQuantityNote: '10 POUND MAX',
  },
  {
    id: 'beef-picada-picada-de-res',
    name: 'Beef Picada/Picada De Res',
    price: 8.59,
    category: 'Beef',
    channel: 'market',
    unit: 'Per lb.',
    maxQuantityNote: '10 POUND MAX',
  },
  {
    id: 'beef-tongue-lengua-de-res',
    name: 'Beef Tongue/Lengua De Res',
    price: 9.89,
    category: 'Beef',
    channel: 'market',
    unit: 'Per lb.',
    maxQuantityNote: '10 POUND MAX',
  },
  {
    id: 'beef-shoulder-clod-espaldilla-de-res',
    name: 'Beef Shoulder Clod/Espaldilla De Res',
    price: 7.99,
    category: 'Beef',
    channel: 'market',
    unit: 'Per lb.',
    maxQuantityNote: '10 POUND MAX',
  },
  {
    id: 'beef-chuck-steak-chuleta-de-res',
    name: 'Beef Chuck Steak/Chuleta De Res',
    price: 7.99,
    category: 'Beef',
    channel: 'market',
    unit: 'Per lb.',
    maxQuantityNote: '10 POUND MAX',
  },
  {
    id: 'bistec-de-bola',
    name: 'Bistec De Bola',
    price: 8.79,
    category: 'Beef',
    channel: 'market',
    unit: 'Per lb.',
    maxQuantityNote: '10 POUND MAX',
  },
  {
    id: 'beef-honeycomb-tripe-menudo-de-panalito',
    name: 'Beef Honeycomb Tripe/Menudo De Panalito',
    price: 7.99,
    category: 'Beef',
    channel: 'market',
    unit: 'Per lb.',
    maxQuantityNote: '10 POUND MAX',
  },
  {
    id: 'beef-tripe-menudo-de-res-regular',
    name: 'Beef Tripe/Menudo De Res Regular',
    price: 4.89,
    category: 'Beef',
    channel: 'market',
    unit: 'Per lb.',
    maxQuantityNote: '10 POUND MAX',
  },
  {
    id: 'beef-feet-patas-de-res',
    name: 'Beef Feet/Patas De Res',
    price: 5.99,
    category: 'Beef',
    channel: 'market',
    unit: 'Per lb.',
    maxQuantityNote: '10 POUND MAX',
  },
  {
    id: 'beef-ribs-costillas-de-res',
    name: 'Beef Ribs/Costillas De Res',
    price: 9.89,
    category: 'Beef',
    channel: 'market',
    unit: 'Per lb.',
    maxQuantityNote: '10 POUND MAX',
  },
  {
    id: 'beef-shank-chamorro-de-res',
    name: 'Beef Shank/Chamorro De Res',
    price: 5.99,
    category: 'Beef',
    channel: 'market',
    unit: 'Per lb.',
    maxQuantityNote: '10 POUND MAX',
  },
];
