import type { MenuItem } from '@/types';

export const beer: MenuItem[] = [
  {
    id: 'modelo-especial-12pk-cans',
    name: 'Modelo Especial',
    price: 19.94,
    category: 'Beer',
    channel: 'market',
    unit: '12/12 FL OZ Cans',
    requiresAgeVerification: true,
  },
  {
    id: 'modelo-chelada-12pk-cans',
    name: 'Modelo Chelada',
    price: 20.99,
    category: 'Beer',
    channel: 'market',
    unit: '12/12 FL OZ Cans',
    requiresAgeVerification: true,
  },
  {
    id: 'modelo-chelada-variety-pk-12pk-cans',
    name: 'Modelo Chelada Variety PK',
    price: 20.99,
    category: 'Beer',
    channel: 'market',
    unit: '12/12 FL OZ Cans',
    requiresAgeVerification: true,
  },
  {
    id: 'tecate-light-12pk-cans',
    name: 'Tecate Light',
    price: 17.63,
    category: 'Beer',
    channel: 'market',
    unit: '12/12 FL OZ Cans',
    requiresAgeVerification: true,
  },
  {
    id: 'sol-12pk-cans',
    name: 'SOL',
    price: 21.2,
    category: 'Beer',
    channel: 'market',
    unit: '12/12 FL OZ Cans',
    requiresAgeVerification: true,
  },
  {
    id: 'famosa-12pk-cans',
    name: 'Famosa',
    price: 24.14,
    category: 'Beer',
    channel: 'market',
    unit: '12/12 FL OZ Cans',
    requiresAgeVerification: true,
  },
  {
    id: 'victoria-12pk-cans',
    name: 'Victoria',
    price: 14.99,
    category: 'Beer',
    channel: 'market',
    unit: '12/12 FL OZ Cans',
    requiresAgeVerification: true,
  },
  {
    id: 'estrella-jalisco-12pk-cans',
    name: 'Estrella Jalisco',
    price: 17.49,
    category: 'Beer',
    channel: 'market',
    unit: '12/12 FL OZ Cans',
    requiresAgeVerification: true,
  },
  {
    id: 'corona-extra-12pk-bottles',
    name: 'Corona Extra',
    price: 21.65,
    category: 'Beer',
    channel: 'market',
    unit: '12/12 FL OZ Bottles',
    requiresAgeVerification: true,
  },
  {
    id: 'famosa-12pk-bottles',
    name: 'Famosa',
    price: 26.25,
    category: 'Beer',
    channel: 'market',
    unit: '12/12 FL OZ Bottles',
    requiresAgeVerification: true,
  },
  {
    id: 'sol-12pk-bottles',
    name: 'SOL',
    price: 17.45,
    category: 'Beer',
    channel: 'market',
    unit: '12/12 FL OZ Bottles',
    requiresAgeVerification: true,
  },
  {
    id: 'pacifico-12pk-bottles',
    name: 'Pacifico',
    price: 19.95,
    category: 'Beer',
    channel: 'market',
    unit: '12/12 FL OZ Bottles',
    requiresAgeVerification: true,
  },
  {
    id: 'estrella-jalisco-12pk-bottles',
    name: 'Estrella Jalisco',
    price: 17.84,
    category: 'Beer',
    channel: 'market',
    unit: '12/12 FL OZ Bottles',
    requiresAgeVerification: true,
  },
  {
    id: 'modelo-especial-32oz',
    name: 'Modelo Especial',
    price: 5.15,
    category: 'Beer',
    channel: 'market',
    unit: '32 FL oz Bottle',
    requiresAgeVerification: true,
  },
  {
    id: 'bud-light-24-fl-oz-bottle',
    name: 'Bud Light',
    price: 4.5,
    category: 'Beer',
    channel: 'market',
    unit: '24 FL oz Bottle',
    requiresAgeVerification: true,
  },
  {
    id: 'michelob-ultra-24-fl-oz-bottle',
    name: 'Michelob Ultra',
    price: 4.25,
    category: 'Beer',
    channel: 'market',
    unit: '24 FL oz Bottle',
    requiresAgeVerification: true,
  },
  {
    id: 'famosa-24oz',
    name: 'Famosa',
    price: 6.08,
    category: 'Beer',
    channel: 'market',
    unit: '24 FL oz Bottle',
    requiresAgeVerification: true,
  },
  {
    id: '805-firestone-walker-24-fl-oz-bottle',
    name: '805 Firestone Walker',
    price: 4.75,
    category: 'Beer',
    channel: 'market',
    unit: '24 FL oz Bottle',
    requiresAgeVerification: true,
  },
  {
    id: 'carta-blanca-24-fl-oz-bottle',
    name: 'Carta Blanca',
    price: 4.65,
    category: 'Beer',
    channel: 'market',
    unit: '24 FL oz Bottle',
    requiresAgeVerification: true,
  },
  {
    id: 'corona-extra-24oz',
    name: 'Corona Extra',
    price: 3.77,
    category: 'Beer',
    channel: 'market',
    unit: '24 oz Bottle',
    requiresAgeVerification: true,
  },
  {
    id: 'modelo-especial-24oz',
    name: 'Modelo Especial',
    price: 3.99,
    category: 'Beer',
    channel: 'market',
    unit: '24 oz Bottle',
    requiresAgeVerification: true,
  },
  {
    id: 'pacifico-32oz',
    name: 'Pacifico',
    price: 4.85,
    category: 'Beer',
    channel: 'market',
    unit: '32 FL oz Bottle',
    requiresAgeVerification: true,
  },
  {
    id: 'victoria-32oz',
    name: 'Victoria',
    price: 5.15,
    category: 'Beer',
    channel: 'market',
    unit: '32 FL oz Bottle',
    requiresAgeVerification: true,
  },
  {
    id: 'corona-familiar-32-fl-oz-bottle',
    name: 'Corona Familiar',
    price: 5.15,
    category: 'Beer',
    channel: 'market',
    unit: '32 FL oz Bottle',
    requiresAgeVerification: true,
  },
];
