import type { MenuItem } from '@/types';

export const marketBeverages: MenuItem[] = [
  {
    id: 'coca-cola-2-ltr',
    name: 'Coca Cola',
    price: 5.35,
    category: 'Beverages',
    channel: 'market',
    unit: '2 ltr',
  },
  {
    id: 'coca-cola-mexican-3-ltr',
    name: 'Coca Cola (Mexican)',
    price: 7.25,
    category: 'Beverages',
    channel: 'market',
    unit: '3 ltr',
  },
  {
    id: 'coca-cola-12-pk',
    name: 'Coca Cola',
    price: 11.7,
    category: 'Beverages',
    channel: 'market',
    unit: '12 pk',
  },
  {
    id: 'coca-cola-20-fl-oz',
    name: 'Coca Cola',
    price: 2.9,
    category: 'Beverages',
    channel: 'market',
    unit: '20 fl oz',
  },
  {
    id: 'mexican-coca-cola-500ml',
    name: 'Mexican Coca Cola',
    price: 4.0,
    category: 'Beverages',
    channel: 'market',
    unit: '500ml',
  },
  {
    id: 'mexican-coca-cola-355ml',
    name: 'Mexican Coca Cola',
    price: 3.15,
    category: 'Beverages',
    channel: 'market',
    unit: '355ml',
  },
  {
    id: 'pepsi-mexicana-500ml',
    name: 'Pepsi Mexicana',
    price: 4.2,
    category: 'Beverages',
    channel: 'market',
    unit: '500ml',
  },
  {
    id: 'pepsi-12-pk',
    name: 'Pepsi',
    price: 11.5,
    category: 'Beverages',
    channel: 'market',
    unit: '12 pk',
  },
  {
    id: 'pepsi-20-fl-oz',
    name: 'Pepsi',
    price: 2.8,
    category: 'Beverages',
    channel: 'market',
    unit: '20 fl oz',
  },
  {
    id: 'pepsi-2-ltrs',
    name: 'Pepsi',
    price: 4.0,
    category: 'Beverages',
    channel: 'market',
    unit: '2 ltrs',
  },
  {
    id: 'squirt-2-ltrs',
    name: 'Squirt',
    price: 4.0,
    category: 'Beverages',
    channel: 'market',
    unit: '2 ltrs',
  },
  {
    id: 'jarritos-mineragua-1-5-ltrs',
    name: 'Jarritos Mineragua',
    price: 3.4,
    category: 'Beverages',
    channel: 'market',
    unit: '1.5 ltrs',
  },
  {
    id: 'jarritos-mandarin-1-5-ltrs',
    name: 'Jarritos Mandarin',
    price: 3.4,
    category: 'Beverages',
    channel: 'market',
    unit: '1.5 ltrs',
  },
  {
    id: 'jarritos-tamarind-1-5-ltrs',
    name: 'Jarritos Tamarind',
    price: 3.4,
    category: 'Beverages',
    channel: 'market',
    unit: '1.5 ltrs',
  },
  {
    id: 'jarritos-mango-1-5-ltrs',
    name: 'Jarritos Mango',
    price: 4.4,
    category: 'Beverages',
    channel: 'market',
    unit: '1.5 ltrs',
  },
  {
    id: 'jarritos-fruit-punch-1-5-ltrs',
    name: 'Jarritos Fruit Punch',
    price: 3.4,
    category: 'Beverages',
    channel: 'market',
    unit: '1.5 ltrs',
  },
  {
    id: 'el-mexicano-agua-de-coco-500ml',
    name: 'El Mexicano Agua De Coco',
    price: 2.15,
    category: 'Beverages',
    channel: 'market',
    unit: '500ml',
  },
];
