import type { MenuItem } from '@/types';

export const canned: MenuItem[] = [
  {
    id: 'teasdale-mexican-style-hominy-30oz',
    name: 'Teasdale Mexican Style Hominy',
    price: 2.95,
    category: 'Canned Products',
    channel: 'market',
    unit: '30oz',
  },
  {
    id: 'teasdale-white-hominy-30oz',
    name: 'Teasdale White Hominy',
    price: 2.9,
    category: 'Canned Products',
    channel: 'market',
    unit: '30oz',
  },
  {
    id: 'el-mexicano-white-hominy-460g',
    name: 'El Mexicano White Hominy',
    price: 2.4,
    category: 'Canned Products',
    channel: 'market',
    unit: '460g',
  },
  {
    id: 'el-mexicano-white-hominy-6lb-10oz',
    name: 'El Mexicano White Hominy',
    price: 6.3,
    category: 'Canned Products',
    channel: 'market',
    unit: '6lb 10oz',
  },
  {
    id: 'el-mexicano-purple-hominy-108oz',
    name: 'El Mexicano Purple Hominy',
    price: 9.05,
    category: 'Canned Products',
    channel: 'market',
    unit: '108oz',
  },
  {
    id: 'teasdale-white-hominy-108oz',
    name: 'Teasdale White Hominy',
    price: 7.34,
    category: 'Canned Products',
    channel: 'market',
    unit: '108oz',
  },
  {
    id: 'el-mexicano-pinto-beans-29-6oz',
    name: 'El Mexicano Pinto Beans',
    price: 3.15,
    category: 'Canned Products',
    channel: 'market',
    unit: '29.6oz',
  },
  {
    id: 'el-mexicano-black-beans-30oz',
    name: 'El Mexicano Black Beans',
    price: 3.35,
    category: 'Canned Products',
    channel: 'market',
    unit: '30oz',
  },
  {
    id: 'la-costena-whole-pinto-beans-29oz',
    name: 'La Costena Whole Pinto Beans',
    price: 4.65,
    category: 'Canned Products',
    channel: 'market',
    unit: '29oz',
  },
  {
    id: 'la-costena-whole-black-beans-29oz',
    name: 'La Costena Whole Black Beans',
    price: 4.85,
    category: 'Canned Products',
    channel: 'market',
    unit: '29oz',
  },
  {
    id: 'el-mexicano-peruvian-beans-30oz',
    name: 'El Mexicano Peruvian Beans',
    price: 3.85,
    category: 'Canned Products',
    channel: 'market',
    unit: '30oz',
  },
  {
    id: 'la-costena-refried-black-beans-28-9oz',
    name: 'La Costena Refried Black Beans',
    price: 5.15,
    category: 'Canned Products',
    channel: 'market',
    unit: '28.9oz',
  },
  {
    id: 'la-costena-refried-pinto-beans-28-9oz',
    name: 'La Costena Refried Pinto Beans',
    price: 4.7,
    category: 'Canned Products',
    channel: 'market',
    unit: '28.9oz',
  },
  {
    id: 'ducal-red-refried-beans-29oz',
    name: 'Ducal Red Refried Beans',
    price: 6.5,
    category: 'Canned Products',
    channel: 'market',
    unit: '29oz',
  },
  {
    id: 'ducal-refried-black-beans-29oz',
    name: 'Ducal Refried Black Beans',
    price: 6.95,
    category: 'Canned Products',
    channel: 'market',
    unit: '29oz',
  },
  {
    id: 'rosarita-spicy-jalapeno-30oz',
    name: 'Rosarita Spicy Jalapeno',
    price: 4.65,
    category: 'Canned Products',
    channel: 'market',
    unit: '30oz',
  },
  {
    id: 'la-costena-sliced-jalapeno-12oz',
    name: 'La Costena Sliced Jalapeno',
    price: 3.4,
    category: 'Canned Products',
    channel: 'market',
    unit: '12oz',
  },
  {
    id: 'la-costena-pickled-jalapeno-12oz',
    name: 'La Costena Pickled Jalapeno',
    price: 2.5,
    category: 'Canned Products',
    channel: 'market',
    unit: '12oz',
  },
  {
    id: 'la-morena-sliced-jalapenos-13-13oz',
    name: 'La Morena Sliced Jalapenos',
    price: 3.0,
    category: 'Canned Products',
    channel: 'market',
    unit: '13.13oz',
  },
  {
    id: 'la-morena-whole-pickled-jalapenos-13-13oz',
    name: 'La Morena Whole Pickled Jalapenos',
    price: 2.3,
    category: 'Canned Products',
    channel: 'market',
    unit: '13.13oz',
  },
  {
    id: 'el-mexicano-sliced-jalapenos-12oz',
    name: 'El Mexicano Sliced Jalapenos',
    price: 2.0,
    category: 'Canned Products',
    channel: 'market',
    unit: '12oz',
  },
  {
    id: 'el-mexicano-whole-jalapeno-peppers-12oz',
    name: 'El Mexicano Whole Jalapeno Peppers',
    price: 2.1,
    category: 'Canned Products',
    channel: 'market',
    unit: '12oz',
  },
  {
    id: 'la-morena-chipotle-peppers-7oz',
    name: 'La Morena Chipotle Peppers',
    price: 2.5,
    category: 'Canned Products',
    channel: 'market',
    unit: '7oz',
  },
  {
    id: 'embasa-chipotle-peppers-7oz',
    name: 'Embasa Chipotle Peppers',
    price: 2.65,
    category: 'Canned Products',
    channel: 'market',
    unit: '7oz',
  },
  {
    id: 'el-mexicano-chipotle-peppers-7-5oz',
    name: 'El Mexicano Chipotle Peppers',
    price: 2.3,
    category: 'Canned Products',
    channel: 'market',
    unit: '7.5oz',
  },
  {
    id: 'la-costena-chipotles-peppers-7oz',
    name: 'La Costena Chipotles Peppers',
    price: 2.6,
    category: 'Canned Products',
    channel: 'market',
    unit: '7oz',
  },
  {
    id: 'el-mexicano-nopalitos-naturales-27oz',
    name: 'El Mexicano Nopalitos Naturales',
    price: 4.2,
    category: 'Canned Products',
    channel: 'market',
    unit: '27oz',
  },
  {
    id: 'dona-maria-nopalitos-30oz',
    name: 'Dona Maria Nopalitos',
    price: 4.85,
    category: 'Canned Products',
    channel: 'market',
    unit: '30oz',
  },
  {
    id: 'el-mexicano-whole-kernel-corn-15-25oz',
    name: 'El Mexicano Whole Kernel Corn',
    price: 1.8,
    category: 'Canned Products',
    channel: 'market',
    unit: '15.25oz',
  },
  {
    id: 'del-monte-whole-kernel-corn-15-25oz',
    name: 'Del Monte Whole Kernel Corn',
    price: 2.7,
    category: 'Canned Products',
    channel: 'market',
    unit: '15.25oz',
  },
  {
    id: 'el-mexicano-mixed-vegetable-15oz',
    name: 'El Mexicano Mixed Vegetable',
    price: 2.3,
    category: 'Canned Products',
    channel: 'market',
    unit: '15oz',
  },
  {
    id: 'del-monte-mixed-vegetables-14-5oz',
    name: 'Del Monte Mixed Vegetables',
    price: 3.0,
    category: 'Canned Products',
    channel: 'market',
    unit: '14.5oz',
  },
  {
    id: 'goya-gandules-verdes-15oz',
    name: 'Goya Gandules Verdes',
    price: 3.25,
    category: 'Canned Products',
    channel: 'market',
    unit: '15oz',
  },
  {
    id: 'del-monte-tomato-sauce-15oz',
    name: 'Del Monte Tomato Sauce',
    price: 2.0,
    category: 'Canned Products',
    channel: 'market',
    unit: '15oz',
  },
  {
    id: 'el-mexicano-garbanzo-beans-15-5oz',
    name: 'El Mexicano Garbanzo Beans',
    price: 2.3,
    category: 'Canned Products',
    channel: 'market',
    unit: '15.5oz',
  },
  {
    id: 'el-mexicano-coconut-milk-13-5floz',
    name: 'El Mexicano Coconut Milk',
    price: 2.65,
    category: 'Canned Products',
    channel: 'market',
    unit: '13.5floz',
  },
  {
    id: 'goya-cream-of-coconut-15oz',
    name: 'Goya Cream Of Coconut',
    price: 2.6,
    category: 'Canned Products',
    channel: 'market',
    unit: '15oz',
  },
];
