import type { MenuItem } from '@/types';

export const cheese: MenuItem[] = [
  {
    id: 'pico-de-gallo',
    name: 'Pico De Gallo',
    price: 4.89,
    category: 'Cheese & Deli',
    channel: 'market',
    unit: '1 lb',
  },
  {
    id: 'el-mexicano-oaxaca',
    name: 'El Mexicano Oaxaca',
    price: 6.0,
    category: 'Cheese & Deli',
    channel: 'market',
    unit: '10oz',
  },
  {
    id: 'el-mexicano-queso-panela',
    name: 'El Mexicano Queso Panela',
    price: 5.9,
    category: 'Cheese & Deli',
    channel: 'market',
    unit: '10oz',
  },
  {
    id: 'el-mexicano-queso-casero',
    name: 'El Mexicano Queso Casero',
    price: 6.3,
    category: 'Cheese & Deli',
    channel: 'market',
    unit: '10oz',
  },
  {
    id: 'el-mexicano-queso-cotija-polvo',
    name: 'El Mexicano Queso Cotija Polvo',
    price: 6.3,
    category: 'Cheese & Deli',
    channel: 'market',
    unit: '10oz',
  },
  {
    id: 'el-mexicano-quesadilla-shredded',
    name: 'El Mexicano Quesadilla Shredded',
    price: 5.9,
    category: 'Cheese & Deli',
    channel: 'market',
    unit: '16oz',
  },
  {
    id: 'el-mexicano-crema-mexicana',
    name: 'El Mexicano Crema Mexicana',
    price: 5.6,
    category: 'Cheese & Deli',
    channel: 'market',
    unit: '15oz',
  },
  {
    id: 'el-mexicano-crema-oaxaquena',
    name: 'El Mexicano Crema Oaxaquena',
    price: 5.6,
    category: 'Cheese & Deli',
    channel: 'market',
    unit: '15oz',
  },
  {
    id: 'el-mexicano-crema-salvadorena',
    name: 'El Mexicano Crema Salvadorena',
    price: 5.6,
    category: 'Cheese & Deli',
    channel: 'market',
    unit: '15oz',
  },
  {
    id: 'crema-mexicana-16oz',
    name: 'El Mexicano Crema Mexicana',
    price: 4.8,
    category: 'Cheese & Deli',
    channel: 'market',
    unit: '16oz',
  },
  {
    id: 'crema-oaxaquena-16oz',
    name: 'El Mexicano Crema Oaxaquena',
    price: 4.8,
    category: 'Cheese & Deli',
    channel: 'market',
    unit: '16oz',
  },
  {
    id: 'pepes-salsa-tatemada-habanero',
    name: "Pepe's Salsa Tatemada Habanero",
    price: 5.2,
    category: 'Cheese & Deli',
    channel: 'market',
    unit: '16oz',
  },
  {
    id: 'pepes-salsa-molcajete-roja',
    name: "Pepe's Salsa Molcajete Roja",
    price: 5.2,
    category: 'Cheese & Deli',
    channel: 'market',
    unit: '16oz',
  },
  {
    id: 'don-pedros-salsa-de-molcajete-verde',
    name: "Don Pedro's Salsa De Molcajete Verde",
    price: 5.3,
    category: 'Cheese & Deli',
    channel: 'market',
    unit: '16oz',
  },
  {
    id: 'don-pedros-salsa-de-aguacate',
    name: "Don Pedro's Salsa De Aguacate",
    price: 5.45,
    category: 'Cheese & Deli',
    channel: 'market',
    unit: '16oz',
  },
];
