import type { MenuItem } from '@/types';

export const dryGoods: MenuItem[] = [
  {
    id: 'el-mexicano-rice-2lbs',
    name: 'El Mexicano Rice',
    price: 3.45,
    category: 'Dry Goods',
    channel: 'market',
    unit: '2lbs',
  },
  {
    id: 'golden-star-jasmine-rice-2lbs',
    name: 'Golden Star Jasmine Rice',
    price: 5.45,
    category: 'Dry Goods',
    channel: 'market',
    unit: '2lbs',
  },
  {
    id: 'premium-jasmine-rice-5lbs',
    name: 'Premium Jasmine Rice',
    price: 12.95,
    category: 'Dry Goods',
    channel: 'market',
    unit: '5lbs',
  },
  {
    id: 'dry-black-beans',
    name: 'El Mexicano Black Beans',
    price: 5.35,
    category: 'Dry Goods',
    channel: 'market',
    unit: '2lbs',
  },
  {
    id: 'dry-pinto-beans',
    name: 'El Mexicano Pinto Beans',
    price: 4.25,
    category: 'Dry Goods',
    channel: 'market',
    unit: '2lbs',
  },
  {
    id: 'el-mexicano-frijol-peruano-2lbs',
    name: 'El Mexicano Frijol Peruano',
    price: 7.25,
    category: 'Dry Goods',
    channel: 'market',
    unit: '2lbs',
  },
  {
    id: 'la-moderna-stars-estrellas-7oz',
    name: 'La Moderna Stars/Estrellas',
    price: 1.0,
    category: 'Dry Goods',
    channel: 'market',
    unit: '7oz',
  },
  {
    id: 'la-moderna-elbows-codos-7oz',
    name: 'La Moderna Elbows/Codos',
    price: 1.0,
    category: 'Dry Goods',
    channel: 'market',
    unit: '7oz',
  },
  {
    id: 'la-moderna-alphabets-letras-7oz',
    name: 'La Moderna Alphabets/Letras',
    price: 1.0,
    category: 'Dry Goods',
    channel: 'market',
    unit: '7oz',
  },
  {
    id: 'la-moderna-vermicelli-7oz',
    name: 'La Moderna Vermicelli',
    price: 1.0,
    category: 'Dry Goods',
    channel: 'market',
    unit: '7oz',
  },
  {
    id: 'la-moderna-fideo-7oz',
    name: 'La Moderna Fideo',
    price: 1.0,
    category: 'Dry Goods',
    channel: 'market',
    unit: '7oz',
  },
];
