import type { MenuItem } from '@/types';

export const grocery: MenuItem[] = [
  {
    id: 'mccormick-mayo-large',
    name: 'McCormick Mayonesa C/Jugo De Limones',
    price: 9.05,
    category: 'Grocery',
    channel: 'market',
    unit: '725g',
  },
  {
    id: 'mccormick-mayo-small',
    name: 'McCormick Mayonesa C/Jugo De Limones',
    price: 4.2,
    category: 'Grocery',
    channel: 'market',
    unit: '7floz',
  },
  {
    id: 'goya-sofrito-12oz',
    name: 'Goya Sofrito',
    price: 4.65,
    category: 'Grocery',
    channel: 'market',
    unit: '12oz',
  },
  {
    id: 'goya-recaito-12oz',
    name: 'Goya Recaito',
    price: 4.65,
    category: 'Grocery',
    channel: 'market',
    unit: '12oz',
  },
  {
    id: 'kikkoman-soy-sauce-5floz',
    name: 'Kikkoman Soy Sauce',
    price: 2.99,
    category: 'Grocery',
    channel: 'market',
    unit: '5floz',
  },
  {
    id: 'maggi-jugo-sazonador-3-38floz',
    name: 'Maggi Jugo Sazonador',
    price: 3.55,
    category: 'Grocery',
    channel: 'market',
    unit: '3.38floz',
  },
  {
    id: 'productos-maya-salsa-inglesa-5floz',
    name: 'Productos Maya Salsa Inglesa',
    price: 3.45,
    category: 'Grocery',
    channel: 'market',
    unit: '5floz',
  },
  {
    id: 'productos-maya-salsa-de-soya-5floz',
    name: 'Productos Maya Salsa De Soya',
    price: 3.45,
    category: 'Grocery',
    channel: 'market',
    unit: '5floz',
  },
  {
    id: 'tajin-lime-large',
    name: 'Tajin With Lime',
    price: 7.0,
    category: 'Grocery',
    channel: 'market',
    unit: '14oz',
  },
  {
    id: 'tajin-lime-small',
    name: 'Tajin With Lime',
    price: 3.85,
    category: 'Grocery',
    channel: 'market',
    unit: '5oz',
  },
  {
    id: 'mazola-corn-oil-40floz',
    name: 'Mazola Corn Oil',
    price: 8.25,
    category: 'Grocery',
    channel: 'market',
    unit: '40floz',
  },
  {
    id: 'el-campesino-extra-virgin-olive-oil-16-9floz',
    name: 'El Campesino Extra Virgin Olive Oil',
    price: 9.8,
    category: 'Grocery',
    channel: 'market',
    unit: '16.9floz',
  },
  {
    id: 'vegetable-oil-1-2-3-33-8floz',
    name: 'Vegetable Oil 1-2-3',
    price: 5.24,
    category: 'Grocery',
    channel: 'market',
    unit: '33.8floz',
  },
  {
    id: 'el-mexicano-white-distilled-vinegar-32floz',
    name: 'El Mexicano White Distilled Vinegar',
    price: 3.15,
    category: 'Grocery',
    channel: 'market',
    unit: '32floz',
  },
  {
    id: 'gamesa-saladitas-42ct',
    name: 'Gamesa Saladitas',
    price: 7.15,
    category: 'Grocery',
    channel: 'market',
    unit: '42ct',
  },
  {
    id: 'gamesa-saladitas-small',
    name: 'Gamesa Saladitas',
    price: 4.2,
    category: 'Grocery',
    channel: 'market',
    unit: '7.3oz',
  },
  {
    id: 'maizena-fecula-de-maiz-14-1oz',
    name: 'Maizena Fecula De Maiz',
    price: 3.5,
    category: 'Grocery',
    channel: 'market',
    unit: '14.1oz',
  },
  {
    id: 'zulka-pure-cane-sugar-4lbs',
    name: 'Zulka Pure Cane Sugar',
    price: 6.2,
    category: 'Grocery',
    channel: 'market',
    unit: '4lbs',
  },
  {
    id: 'ch-pure-granulated-sugar-4lbs',
    name: 'C&H Pure Granulated Sugar',
    price: 6.5,
    category: 'Grocery',
    channel: 'market',
    unit: '4lbs',
  },
  {
    id: 'pan-pre-cooked-white-corn-meal-5lbs',
    name: 'P.A.N Pre-Cooked White Corn Meal',
    price: 9.5,
    category: 'Grocery',
    channel: 'market',
    unit: '5lbs',
  },
  {
    id: 'maseca-instant-corn-masa-flour-4lbs',
    name: 'Maseca Instant Corn Masa Flour',
    price: 6.95,
    category: 'Grocery',
    channel: 'market',
    unit: '4lbs',
  },
  {
    id: 'goya-rice-flour-24oz',
    name: 'Goya Rice Flour',
    price: 4.1,
    category: 'Grocery',
    channel: 'market',
    unit: '24oz',
  },
  {
    id: 'royal-baking-powder-8-1oz',
    name: 'Royal Baking Powder',
    price: 4.2,
    category: 'Grocery',
    channel: 'market',
    unit: '8.1oz',
  },
  {
    id: 'armour-lard-manteca-40oz',
    name: 'Armour Lard/Manteca',
    price: 9.05,
    category: 'Grocery',
    channel: 'market',
    unit: '40oz',
  },
  {
    id: 'morton-salt-26oz',
    name: 'Morton Salt',
    price: 2.95,
    category: 'Grocery',
    channel: 'market',
    unit: '26oz',
  },
  {
    id: 'amorcito-corazon-sea-salt-24-64oz',
    name: 'Amorcito Corazon Sea Salt',
    price: 3.2,
    category: 'Grocery',
    channel: 'market',
    unit: '24.64oz',
  },
  {
    id: 'nestle-la-lechera-375g',
    name: 'Nestle La Lechera',
    price: 3.1,
    category: 'Grocery',
    channel: 'market',
    unit: '375g',
  },
  {
    id: 'nestle-carnation-leche-evaporada-360g',
    name: 'Nestle Carnation Leche Evaporada',
    price: 3.0,
    category: 'Grocery',
    channel: 'market',
    unit: '360g',
  },
  {
    id: 'nestle-media-crema-225g',
    name: 'Nestle Media Crema',
    price: 3.65,
    category: 'Grocery',
    channel: 'market',
    unit: '225g',
  },
  {
    id: 'nestle-abuelita-19oz',
    name: 'Nestle Abuelita',
    price: 8.4,
    category: 'Grocery',
    channel: 'market',
    unit: '19oz',
  },
  {
    id: 'ibarra-chocolate-17oz',
    name: 'Ibarra Chocolate',
    price: 8.5,
    category: 'Grocery',
    channel: 'market',
    unit: '17oz',
  },
  {
    id: 'el-mexicano-natural-bee-honey-16oz',
    name: 'El Mexicano Natural Bee Honey',
    price: 11.55,
    category: 'Grocery',
    channel: 'market',
    unit: '16oz',
  },
  {
    id: 'molina-mexican-vanilla-blend-8-3floz',
    name: 'Molina Mexican Vanilla Blend',
    price: 3.8,
    category: 'Grocery',
    channel: 'market',
    unit: '8.3floz',
  },
  {
    id: 'clamato-picante-32floz',
    name: 'Clamato Picante',
    price: 4.6,
    category: 'Grocery',
    channel: 'market',
    unit: '32floz',
  },
  {
    id: 'clamato-original-946ml',
    name: 'Clamato Original',
    price: 5.3,
    category: 'Grocery',
    channel: 'market',
    unit: '946ml',
  },
];
