import type { MenuItem } from '@/types';

export const hotSauces: MenuItem[] = [
  {
    id: 'valentina-extra-hot-12-5floz',
    name: 'Valentina Extra Hot',
    price: 2.65,
    category: 'Hot Sauces',
    channel: 'market',
    unit: '12.5floz',
  },
  {
    id: 'valentina-salsa-picante-12-5floz',
    name: 'Valentina Salsa Picante',
    price: 2.75,
    category: 'Hot Sauces',
    channel: 'market',
    unit: '12.5floz',
  },
  {
    id: 'tapatio-salsa-picante-5floz',
    name: 'Tapatio Salsa Picante',
    price: 1.75,
    category: 'Hot Sauces',
    channel: 'market',
    unit: '5floz',
  },
  {
    id: 'el-yucateco-xxxtra-hot-sauce-4floz',
    name: 'El Yucateco XXXtra Hot Sauce',
    price: 3.85,
    category: 'Hot Sauces',
    channel: 'market',
    unit: '4floz',
  },
  {
    id: 'el-yucateco-chile-habanero-verde-4floz',
    name: 'El Yucateco Chile Habanero Verde',
    price: 3.85,
    category: 'Hot Sauces',
    channel: 'market',
    unit: '4floz',
  },
  {
    id: 'el-yucateco-chile-habanero-rojo-4floz',
    name: 'El Yucateco Chile Habanero Rojo',
    price: 3.85,
    category: 'Hot Sauces',
    channel: 'market',
    unit: '4floz',
  },
  {
    id: 'el-yucateco-chile-habanero-black-label-4floz',
    name: 'El Yucateco Chile Habanero Black Label',
    price: 3.95,
    category: 'Hot Sauces',
    channel: 'market',
    unit: '4floz',
  },
  {
    id: 'salsa-huichol-habanera-6floz',
    name: 'Salsa Huichol Habanera',
    price: 2.75,
    category: 'Hot Sauces',
    channel: 'market',
    unit: '6floz',
  },
  {
    id: 'salsa-huichol-hot-sauce-6floz',
    name: 'Salsa Huichol Hot Sauce',
    price: 2.25,
    category: 'Hot Sauces',
    channel: 'market',
    unit: '6floz',
  },
  {
    id: 'culichi-negra-6-8floz',
    name: 'Culichi Negra',
    price: 3.25,
    category: 'Hot Sauces',
    channel: 'market',
    unit: '6.8floz',
  },
  {
    id: 'herdez-roasted-salsa-verde-15-7oz',
    name: 'Herdez Roasted Salsa Verde',
    price: 4.95,
    category: 'Hot Sauces',
    channel: 'market',
    unit: '15.7oz',
  },
  {
    id: 'herdez-roasted-salsa-roja-15-7oz',
    name: 'Herdez Roasted Salsa Roja',
    price: 4.95,
    category: 'Hot Sauces',
    channel: 'market',
    unit: '15.7oz',
  },
  {
    id: 'herdez-guacamole-salsa-15-7oz',
    name: 'Herdez Guacamole Salsa',
    price: 5.25,
    category: 'Hot Sauces',
    channel: 'market',
    unit: '15.7oz',
  },
  {
    id: 'el-mexicano-salsa-verde-17-6oz',
    name: 'El Mexicano Salsa Verde',
    price: 4.39,
    category: 'Hot Sauces',
    channel: 'market',
    unit: '17.6oz',
  },
  {
    id: 'el-mexicano-salsa-mexicana-17-6oz',
    name: 'El Mexicano Salsa Mexicana',
    price: 4.35,
    category: 'Hot Sauces',
    channel: 'market',
    unit: '17.6oz',
  },
  {
    id: 'el-mexicano-salsa-taquera-17-6oz',
    name: 'El Mexicano Salsa Taquera',
    price: 4.35,
    category: 'Hot Sauces',
    channel: 'market',
    unit: '17.6oz',
  },
  {
    id: 'el-mexicano-salsa-guacamole-17-6oz',
    name: 'El Mexicano Salsa Guacamole',
    price: 4.55,
    category: 'Hot Sauces',
    channel: 'market',
    unit: '17.6oz',
  },
  {
    id: 'chamoy-mega-original-33-8floz',
    name: 'Chamoy Mega Original',
    price: 3.65,
    category: 'Hot Sauces',
    channel: 'market',
    unit: '33.8floz',
  },
];
