import type { MenuItem } from '@/types';

export const pork: MenuItem[] = [
  {
    id: 'pork-feet-patas-de-puerco',
    name: 'Pork Feet/Patas De Puerco',
    price: 2.89,
    category: 'Pork',
    channel: 'market',
    unit: 'lb',
  },
  {
    id: 'pork-neck-bones-espinazo-de-puerco',
    name: 'Pork Neck Bones/Espinazo De Puerco',
    price: 2.99,
    category: 'Pork',
    channel: 'market',
    unit: 'lb',
  },
  {
    id: 'pork-butt-espaldilla-de-puerco',
    name: 'Pork Butt/Espaldilla De Puerco',
    price: 3.89,
    category: 'Pork',
    channel: 'market',
    unit: 'lb',
  },
  {
    id: 'boneless-pork-leg-pierna-de-puerco-sin-hueso',
    name: 'Boneless Pork Leg/Pierna De Puerco Sin Hueso',
    price: 3.59,
    category: 'Pork',
    channel: 'market',
    unit: 'lb',
  },
  {
    id: 'pork-spareribs-costilla-de-puerco',
    name: 'Pork Spareribs/Costilla De Puerco',
    price: 3.89,
    category: 'Pork',
    channel: 'market',
    unit: 'lb',
  },
  {
    id: 'pork-chops-chuletas-de-puerco',
    name: 'Pork Chops/Chuletas De Puerco',
    price: 3.29,
    category: 'Pork',
    channel: 'market',
    unit: 'lb',
  },
  {
    id: 'smoked-pork-loin-chuletas-ahumadas',
    name: 'Smoked Pork Loin/Chuletas Ahumadas',
    price: 4.99,
    category: 'Pork',
    channel: 'market',
    unit: 'lb',
  },
  {
    id: 'marinated-adobada-carne-adobada',
    name: 'Marinated Adobada/Carne Adobada',
    price: 5.69,
    category: 'Pork',
    channel: 'market',
    unit: 'lb',
  },
  {
    id: 'dried-chorizo-chorizo-seco',
    name: 'Dried Chorizo/Chorizo Seco',
    price: 6.99,
    category: 'Pork',
    channel: 'market',
    unit: 'lb',
  },
  {
    id: 'fresh-chorizo-chorizo-fresco',
    name: 'Fresh Chorizo/Chorizo Fresco',
    price: 6.99,
    category: 'Pork',
    channel: 'market',
    unit: 'lb',
  },
  {
    id: 'fud-turkey-ham-jamon-de-pavo-fud',
    name: 'Fud Turkey Ham/Jamon De Pavo Fud',
    price: 6.79,
    category: 'Pork',
    channel: 'market',
    unit: 'Per lb.',
  },
  {
    id: 'fud-original-ham-jamon-original',
    name: 'Fud Original Ham/Jamon Original',
    price: 6.79,
    category: 'Pork',
    channel: 'market',
    unit: 'Per lb.',
  },
  {
    id: 'fud-pork-head-cheese-queso-de-puerco',
    name: 'Fud Pork Head Cheese/Queso De Puerco',
    price: 6.79,
    category: 'Pork',
    channel: 'market',
    unit: 'Per lb.',
  },
];
