import type { MenuItem } from '@/types';

export const poultry: MenuItem[] = [
  {
    id: 'drumsticks',
    name: 'Drumsticks',
    price: 2.69,
    category: 'Poultry',
    channel: 'market',
    unit: 'per pound',
  },
  {
    id: 'marinated-chicken-breast-pechuga-de-pollo-marinado',
    name: 'Marinated Chicken Breast/Pechuga De Pollo Marinado',
    price: 5.99,
    category: 'Poultry',
    channel: 'market',
    unit: 'Per lb.',
  },
  {
    id: 'marinated-diced-chicken-pollo-marinado-picado',
    name: 'Marinated Diced Chicken/Pollo Marinado Picado',
    price: 5.99,
    category: 'Poultry',
    channel: 'market',
    unit: 'Per lb.',
  },
  {
    id: 'whole-chicken-breast-pechuga-de-pollo-con-hueso',
    name: 'Whole Chicken Breast/Pechuga De Pollo Con Hueso',
    price: 3.89,
    category: 'Poultry',
    channel: 'market',
    unit: 'Per lb.',
  },
  {
    id: 'boneless-chicken-breast-pechuga-de-pollo-sin-hueso',
    name: 'Boneless Chicken Breast/Pechuga De Pollo Sin Hueso',
    price: 5.59,
    category: 'Poultry',
    channel: 'market',
    unit: 'Per lb.',
  },
  {
    id: 'chicken-leg-quarters-pierna-y-muslo-de-pollo',
    name: 'Chicken Leg Quarters/Pierna Y Muslo De Pollo',
    price: 1.89,
    category: 'Poultry',
    channel: 'market',
    unit: 'Per lb.',
  },
  {
    id: 'chicken-wings-alas',
    name: 'Chicken Wings/Alas',
    price: 4.89,
    category: 'Poultry',
    channel: 'market',
    unit: 'Per lb.',
  },
  {
    id: 'chicken-feet-patas',
    name: 'Chicken Feet/Patas',
    price: 4.39,
    category: 'Poultry',
    channel: 'market',
    unit: 'Per lb.',
  },
  {
    id: 'stewing-chicken-pollo-rancho',
    name: 'Stewing Chicken/Pollo Rancho',
    price: 17.99,
    category: 'Poultry',
    channel: 'market',
    unit: 'ea',
  },
];
