import type { MenuItem } from '@/types';

export const produce: MenuItem[] = [
  {
    id: 'cilantro',
    name: 'Cilantro',
    price: 0.79,
    category: 'Produce',
    channel: 'market',
    unit: 'ea',
  },
  {
    id: 'yerba-buena',
    name: 'Yerba Buena',
    price: 2.19,
    category: 'Produce',
    channel: 'market',
    unit: 'ea',
  },
  {
    id: 'epazote',
    name: 'Epazote',
    price: 2.19,
    category: 'Produce',
    channel: 'market',
    unit: 'ea',
  },
  {
    id: 'mexican-green-onion-cebollitas',
    name: 'Mexican Green Onion/Cebollitas',
    price: 1.0,
    category: 'Produce',
    channel: 'market',
    unit: 'ea',
  },
  {
    id: 'white-onion-cebolla-blanca',
    name: 'White Onion/Cebolla Blanca',
    price: 0.8,
    category: 'Produce',
    channel: 'market',
    unit: 'ea',
  },
  {
    id: 'yellow-onion-cebolla-amarillo',
    name: 'Yellow Onion/Cebolla Amarillo',
    price: 0.7,
    category: 'Produce',
    channel: 'market',
    unit: 'ea',
  },
  {
    id: 'red-onion-cebolla-morada',
    name: 'Red Onion/Cebolla Morada',
    price: 0.4,
    category: 'Produce',
    channel: 'market',
    unit: 'ea',
  },
  {
    id: 'avocado-aguacate',
    name: 'Avocado/Aguacate',
    price: 0.99,
    category: 'Produce',
    channel: 'market',
    unit: 'ea',
  },
  {
    id: 'lime-limon-verde',
    name: 'Lime/Limon Verde',
    price: 0.45,
    category: 'Produce',
    channel: 'market',
    unit: 'ea',
  },
  {
    id: 'yellow-lemon-limon-amarillo',
    name: 'Yellow Lemon/Limon Amarillo',
    price: 0.59,
    category: 'Produce',
    channel: 'market',
    unit: 'ea',
  },
  {
    id: 'chile-jalapeno',
    name: 'Chile Jalapeno',
    price: 0.15,
    category: 'Produce',
    channel: 'market',
    unit: 'ea',
  },
  {
    id: 'chile-serrano',
    name: 'Chile Serrano',
    price: 0.1,
    category: 'Produce',
    channel: 'market',
    unit: 'ea',
  },
  {
    id: 'poblano-pepper-chile-poblano',
    name: 'Poblano Pepper/Chile Poblano',
    price: 0.85,
    category: 'Produce',
    channel: 'market',
    unit: 'ea',
  },
  {
    id: 'green-bell-pepper',
    name: 'Green Bell Pepper',
    price: 1.29,
    category: 'Produce',
    channel: 'market',
    unit: 'ea',
  },
  {
    id: 'red-bell-pepper',
    name: 'Red Bell Pepper',
    price: 1.15,
    category: 'Produce',
    channel: 'market',
    unit: 'ea',
  },
  {
    id: 'roma-tomato-jitomate-roma',
    name: 'Roma Tomato/Jitomate Roma',
    price: 0.8,
    category: 'Produce',
    channel: 'market',
    unit: 'ea',
  },
  {
    id: 'tomato-jitomate',
    name: 'Tomato/Jitomate',
    price: 1.45,
    category: 'Produce',
    channel: 'market',
    unit: 'ea',
  },
  {
    id: 'tomatillo',
    name: 'Tomatillo',
    price: 0.3,
    category: 'Produce',
    channel: 'market',
    unit: 'ea',
  },
  {
    id: 'peeled-tomatillos-tomatillos-pelados',
    name: 'Peeled Tomatillos/Tomatillos Pelados',
    price: 0.6,
    category: 'Produce',
    channel: 'market',
    unit: 'ea',
  },
  {
    id: 'tomatillo-milpero',
    name: 'Tomatillo Milpero',
    price: 2.69,
    category: 'Produce',
    channel: 'market',
    unit: 'bag',
  },
  {
    id: 'garlic-bag-5ct-bolsa-de-ajo-5pc',
    name: 'Garlic Bag 5ct/Bolsa De Ajo 5pc',
    price: 2.69,
    category: 'Produce',
    channel: 'market',
    unit: 'ea bag',
  },
  {
    id: 'radishes-rabanos',
    name: 'Radishes/Rabanos',
    price: 2.19,
    category: 'Produce',
    channel: 'market',
    unit: 'ea bag',
  },
  {
    id: 'mexican-squash-calabaza-mexicana',
    name: 'Mexican Squash/Calabaza Mexicana',
    price: 0.4,
    category: 'Produce',
    channel: 'market',
    unit: 'ea',
  },
  {
    id: 'chayote',
    name: 'Chayote',
    price: 0.7,
    category: 'Produce',
    channel: 'market',
    unit: 'ea',
  },
  {
    id: 'russet-potato-papa-russet',
    name: 'Russet Potato/Papa Russet',
    price: 0.6,
    category: 'Produce',
    channel: 'market',
    unit: 'ea',
  },
  {
    id: 'white-potato-papa-blanca',
    name: 'White Potato/Papa Blanca',
    price: 0.8,
    category: 'Produce',
    channel: 'market',
    unit: 'ea',
  },
  {
    id: 'carrot-bag-bolsa-de-zanahoria',
    name: 'Carrot Bag/Bolsa De Zanahoria',
    price: 1.15,
    category: 'Produce',
    channel: 'market',
    unit: 'ea',
  },
  {
    id: 'corn-elote',
    name: 'Corn/Elote',
    price: 1.39,
    category: 'Produce',
    channel: 'market',
    unit: 'ea',
  },
  {
    id: 'green-cabbage-repollo-verde',
    name: 'Green Cabbage/Repollo Verde',
    price: 2.0,
    category: 'Produce',
    channel: 'market',
    unit: 'ea',
  },
  {
    id: 'lettuce-lechuga',
    name: 'Lettuce/Lechuga',
    price: 2.19,
    category: 'Produce',
    channel: 'market',
    unit: 'ea',
  },
  {
    id: 'cucumber-pepino',
    name: 'Cucumber/Pepino',
    price: 0.99,
    category: 'Produce',
    channel: 'market',
    unit: 'ea',
  },
  {
    id: 'nopal-entero-pelado-3pc',
    name: 'Nopal Entero Pelado 3pc',
    price: 2.59,
    category: 'Produce',
    channel: 'market',
    unit: 'ea',
  },
  {
    id: 'nopal-picado-charola',
    name: 'Nopal Picado',
    price: 2.99,
    category: 'Produce',
    channel: 'market',
    unit: 'charola',
  },
  {
    id: 'banana-platano',
    name: 'Banana/Platano',
    price: 2.99,
    category: 'Produce',
    channel: 'market',
    unit: 'bunch',
  },
  {
    id: 'orange-naranja',
    name: 'Orange/Naranja',
    price: 0.59,
    category: 'Produce',
    channel: 'market',
    unit: 'ea',
  },
];
