import type { MenuItem } from '@/types';

export const tortillas: MenuItem[] = [
  {
    id: 'guerrero-corn-tortillas-100ct',
    name: 'Guerrero Corn Tortillas',
    price: 6.3,
    category: 'Tortillas & Tostadas',
    channel: 'market',
    unit: '100ct',
  },
  {
    id: 'guerrero-corn-tortillas-80ct',
    name: 'Guerrero Corn Tortillas',
    price: 5.3,
    category: 'Tortillas & Tostadas',
    channel: 'market',
    unit: '80ct',
  },
  {
    id: 'guerrero-corn-tortillas-30ct',
    name: 'Guerrero Corn Tortillas',
    price: 3.3,
    category: 'Tortillas & Tostadas',
    channel: 'market',
    unit: '30ct',
  },
  {
    id: 'guerrero-king-size-30ct',
    name: 'Guerrero King Size',
    price: 4.0,
    category: 'Tortillas & Tostadas',
    channel: 'market',
    unit: '30ct',
  },
  {
    id: 'guerrero-tortillas-taqueria-style-60ct',
    name: 'Guerrero Tortillas Taqueria Style',
    price: 4.2,
    category: 'Tortillas & Tostadas',
    channel: 'market',
    unit: '60ct',
  },
  {
    id: 'guerrero-caseras-flour-tortillas-20ct',
    name: 'Guerrero Caseras Flour Tortillas',
    price: 3.5,
    category: 'Tortillas & Tostadas',
    channel: 'market',
    unit: '20ct',
  },
  {
    id: 'guerrero-riquisimas-flour-tortillas-24ct',
    name: 'Guerrero Riquisimas Flour Tortillas',
    price: 7.0,
    category: 'Tortillas & Tostadas',
    channel: 'market',
    unit: '24ct',
  },
  {
    id: 'guerrero-tostadas-caseras-amarillas-22ct',
    name: 'Guerrero Tostadas Caseras Amarillas',
    price: 4.1,
    category: 'Tortillas & Tostadas',
    channel: 'market',
    unit: '22ct',
  },
  {
    id: 'guerrero-tostadas-nortenas-30ct',
    name: 'Guerrero Tostadas Nortenas',
    price: 4.1,
    category: 'Tortillas & Tostadas',
    channel: 'market',
    unit: '30ct',
  },
  {
    id: 'la-rosa-tortilla-original-casera-70oz',
    name: 'La Rosa Tortilla Original Casera',
    price: 7.7,
    category: 'Tortillas & Tostadas',
    channel: 'market',
    unit: '70oz',
  },
  {
    id: 'la-rosa-corn-tortillas-la-grande-60oz',
    name: 'La Rosa Corn Tortillas La Grande',
    price: 6.1,
    category: 'Tortillas & Tostadas',
    channel: 'market',
    unit: '60oz',
  },
  {
    id: 'la-rosa-corn-tortillas-la-grande-40oz',
    name: 'La Rosa Corn Tortillas La Grande',
    price: 4.5,
    category: 'Tortillas & Tostadas',
    channel: 'market',
    unit: '40oz',
  },
  {
    id: 'la-rosa-taquito-style-1lb',
    name: 'La Rosa Taquito Style',
    price: 3.6,
    category: 'Tortillas & Tostadas',
    channel: 'market',
    unit: '1lb',
  },
  {
    id: 'la-rosa-totopos-estilo-casero-16oz',
    name: 'La Rosa Totopos Estilo Casero',
    price: 4.5,
    category: 'Tortillas & Tostadas',
    channel: 'market',
    unit: '16oz',
  },
  {
    id: 'la-rosa-tostadas-nuevo-sabor-10oz',
    name: 'La Rosa Tostadas Nuevo Sabor',
    price: 4.4,
    category: 'Tortillas & Tostadas',
    channel: 'market',
    unit: '10oz',
  },
  {
    id: 'la-rosa-tostadas-10oz',
    name: 'La Rosa Tostadas',
    price: 4.5,
    category: 'Tortillas & Tostadas',
    channel: 'market',
    unit: '10oz',
  },
];
